start_delay: 2.0

pi_x: -0.3
pi_y: -0.3
pi_z: 0.3
oi_x: 0.0
oi_y: 0.0
oi_z: 0.0
oi_w: 1.0

pf_x: 0.2
pf_y: 0.4
pf_z: 0.5
of_x: 0.0
of_y: 0.0
of_z: 0.0
of_w: 1.0

weight_ox: 0.0
weight_oy: 0.0
weight_oz: 0.0
weight_px: 1.0
weight_py: 1.0
weight_pz: 1.0
