start_delay: 2.0
max_ang_vel: 1.0
max_ang_acc: 0.5

n_points: 5

pi_x: 0.0
pi_y: 0.0
pi_z: 0.99
oi_x: 0.0
oi_y: 0.0
oi_z: 0.0
oi_w: 1.0

pf_x: 0.3
pf_y: 0.3
pf_z: 0.3
of_x: 0.0
of_y: 0.0
of_z: 0.0
of_w: 1.0

pos_control_1: 0.2
pos_control_2: 0.2
pos_control_3: 0.2
pos_control_4: 0.2
pos_control_5: 0.2
pos_control_6: 0.2
