controller_joint_name_1: 'edo_joint_1'
controller_joint_name_2: 'edo_joint_2'
controller_joint_name_3: 'edo_joint_3'
controller_joint_name_4: 'edo_joint_4'
controller_joint_name_5: 'edo_joint_5'
controller_joint_name_6: 'edo_joint_6'
