q1_initial: 0.0
q2_initial: 0.0
q3_initial: 0.0
q4_initial: 0.0
q5_initial: 0.0
q6_initial: 0.0

q1_final: 6.28
q2_final: 6.28
q3_final: 6.28
q4_final: 6.28
q5_final: 6.28
q6_final: 6.28

trajectoryType: 2

start_delay: 5.0
tf: 20.0

max_ang_vel: 5.0
max_ang_acc: 2.0

